### PR TITLE
Doc as test

### PR DESCRIPTION
**Pull request by sfauvel**
I try to use approval to generate asciidoc and create a page to group all tests of a class in a single page.
I just want to share the result with you. It's not to merge to your repo.
You can look at docs/test_jewellery_storage.approved.adoc and docs/test_necklace_packing.approved.adoc.
It's probably not the best representation but I ask only to have other proposals

### CODE REVIEW

**Comment by codecop** [comment]
This PR is for discussing another approach and not meant to be merged. @emilybache I guess you can close if after inspection.

**Comment by emilybache** [comment]
I am grateful for the PR, apologies for not noticing it sooner. I intend to look at it more closely.

**Comment by sfauvel** [comment]
I rebased from main and add an example to see in the same table where each item goes. 
I pushed force for that. I hope I didn't break anything.

**Comment by codecop** [comment]
The PR still stays for documentation if it is closed. @emilybache could we close please, so it is not showing up in list of open PRs?

**Pull request closed without merging**
